version: '3.9'
services:
  db:
    image: mariadb:10.8.3-jammy
    restart: on-failure
    ports:
      - '3306:3306'
    env_file: 
      - .env
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'
  nginx:
    image: nginx:1.21.6-alpine
    restart: on-failure
    volumes: 
      - './application/web:/usr/src/app/web'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
    ports:
      - '80:80'
  php: 
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './application:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    user: 1000:1000
  node:
    image: node:16.15.1
    build:
      context: . 
      dockerfile: docker/node/Dockerfile
    volumes:
      - './application:/usr/src/app'
    restart: on-failure
